### ISSUE TITLE
CI failing with `RuntimeError: missing a data folder with submission date`

### ISSUE THREAD

**Issue by fbertsch** [mozilla-services/mozilla-pipeline-schemas#625]
Most recent failure: https://app.circleci.com/pipelines/github/mozilla-services/mozilla-pipeline-schemas/2071/workflows/5fa2b507-7e12-4d2d-9d4e-7644a1105d3e/jobs/4430

```
Traceback (most recent call last):
  File "integration.py", line 344, in <module>
    integrate()
  File "/app/.venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/app/.venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/app/.venv/lib/python3.6/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/app/.venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "integration.py", line 334, in compare_cmd
    rev_a_path = _run_report(rev_a)
  File "integration.py", line 327, in _run_report
    Reporter().run(data_path, output_path)
  File "integration.py", line 151, in run
    raise RuntimeError("missing a data folder with submission date")
RuntimeError: missing a data folder with submission date

```

**Comment by fbertsch** [comment]
cc @acmiyaguchi are you able to take a look?

**Comment by acmiyaguchi** [comment]
This is because the v1.4.0 container relies on the old sanitized-landfill-sample in AWS which is no longer a thing. The v1.5.0 container has support for reading from the monitoring dataset in shared prod instead, but there are security implications with allowing data to leave GCP (see https://github.com/mozilla-services/edge-validator/pull/46).

I'd like to opt to remove the edge-validator as a dependency (and perhaps archive the repo), while adding in a cloudrun function here to completely replace it. In the meanwhile, there won't be any CI that runs on real data.

**Comment by acmiyaguchi** [comment]
I filed #644 for what I would like to see to replace the edge-validator in CI here.
